### ISSUE TITLE
Validate correctness of tie handling

### ISSUE THREAD

**Issue by JonasHanselle** [KIuML/weighted_rank_correlation#5]
Ranking [1,1,2], [1,2,3]

**Comment by stheid** [comment]
https://github.com/KIuML/weighted_rank_correlation/blob/761a4bbe470d61a7741dd69f8d226742bd81345b/scaled_gamma.py#L226-L235 Ties have no effect on the outcome of the correltion measure

**Comment by stheid** [comment]
From the paper it gets clear that the correlation is not influenced by the ties, therefore it does not need to get computed
